### PR TITLE
Fix plugin for N900

### PR DESCRIPTION
**Pull request by spinal84**
* Fallback to voltage measurement if battery is not calibrated
  * Make plugin look and feel more like Fremantle's original one when
    use_design_capacity option is off
  * Add UPower charger device support
  * Misc fixes and improvements

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
I've merged this to maemo/ascii-devel - any clue why this fails? https://phoenix.maemo.org/job/status-area-applet-battery-binaries/architecture=amd64,label=amd64/2/console

Does it need a newer upower?

**Comment by spinal84** [comment]
There are different versions of UPower packaged for amd64 and armhf architectures in current Devuan stable (ascii) release.
 
These versions are incompatible. Some stuff in amd64 version is missing that is introduced in upstream/debian/armhf packages.
 
That what is packaged in devuan ascii armhf:
Package: upower
Version: 0.99.4-4+b1
Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Architecture: armhf
 
And that's in devuan ascii amd64:
Package: upower
Version: 1:0.9.23-2+devuan1.3
Maintainer: Daniel Reurich <daniel@devuan.org>
Architecture: amd64

The version packaged for amd64 is probably meant to be Devuan mainstream. As I can understand they took a very old outdated version of UPower, applied some anti-systemd patches and packaged it to amd64 and maybe some other architectures. But they forget to do the same thing for armhf and maybe some other archs. So the problem is a diversion from Devuan repositories.

You took current Debian maintained version of UPower which is still packaged by Devuan (probably by mistake) on armhf as a base for Maemo Leste for all architectures. But this version is ovewritten by Devuan package for amd64 because they increase epoch to 1 (look at the "1:" part of the version).

I tried to contact Devuan maintainer <daniel@devuan.org> about the issue, but got the error:
<daniel@devuan.org>: Recipient address rejected: User unknown in virtual mailbox table.

That's it.

**Comment by MerlijnWajer** [comment]
New upower in our repo now makes this build. It's in leste-devel, and it seems to work well on my N900.
Code looks very good, commits are well structured. Awesome work. I have one question and one note:

Question: Did you run it standalone in valgrind for a bit? (To check for memory leaks)
Note: We should try to minimalise the device-specific code (blacklist and also the whitelist rx51-battery, I think I saw a check in rx51-battery check in the code somewhere).

**Comment by MerlijnWajer** [comment]
And if we have device specific blacklist/whitelist, perhaps they should be in a separate file (structs) or at the top somewhere, but not inline checks. So that it's clear.

**Comment by spinal84** [comment]
> Question: Did you run it standalone in valgrind for a bit? (To check for memory leaks)

No, I didn't

> Note: We should try to minimalise the device-specific code (blacklist and also the whitelist rx51-battery, I think I saw a check in rx51-battery check in the code somewhere).

There's no device specific code. Blacklist for bq27200 appeared in one commit, but I removed it after a while.
So the code should be generic now.

**Comment by MerlijnWajer** [comment]
Alright, sorry that I missed that. I indeed went through the commits one by one in tig. As for valgrind: it's probably fine for now. I've been using it in leste-devel and it works nicely on the N900 (much better than before).

**Pull request closed without merging**
